# Default values for gwms.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


#----------------------------------------------------------------------------------#
# Host-related values: these values refer to the node running the                  #
# kubernetes cluster, and the current implementation assumes a single-node cluster #
#----------------------------------------------------------------------------------#

# hostHostname is the hostname of the node running the kubernetes cluster.
# It is used for inter-pod networking, persistent mount assignment, and token filenames.
hostHostname: 

# hostIPv4 is the IPv4 address of the node running the kubernetes cluster.
# It is used to expose kubernetes Services to the internet.
hostIPv4: 

# hostIPv6 is the IPv6 address of the node running the kubernetes cluster.
# It is used to expose kubernetes Services to the internet.
hostIPv6: 


#-----------------------------------------------------------------------------------------------------------------#
# Scitoken-related values: these values are passed to htgettoken as command-line arguments to automatically renew #
# scitokens. If you require additional customization, please modify config/de/renew_scitoken.sh directly    #
# See also: https://htmlpreview.github.io/?https://github.com/fermitools/htgettoken/blob/master/htgettoken.html   #
#-----------------------------------------------------------------------------------------------------------------#

# oidcTokenIssuer is the organization issuing scitokens, passed to the -i argument of htgettoken
oidcTokenIssuer: 

# vaultServer is the hostname or URL of the vault server issuing scitokens, passed to the -a argument of htgettoken
vaultServer: 


#----------------------------------------------------------------------------------------------------------#
# ConfigMap paths: these values are used to create kubernetes ConfigMaps with read-only information to be  #
# passed to the pods. They must be expressed as relative paths from the root directory of this Helm chart. # 
#----------------------------------------------------------------------------------------------------------#

# condorConfigMountRoot is the relative path to the directory containing configuration files for the HTCondor central manager
condorConfigMountRoot: config/condor

# condorCertsMountRoot is the relative path to the directory containing X.509 certificates for the HTCondor central manager
condorCertsMountRoot: config/condor/certs

# deConfigMountRoot is the relative path to the directory containing configuration files for the HEPCloud decisionengine
deConfigMountRoot: config/de

# deCertsMountRoot is the relative path to the directory containing X.509 certificates for the HEPCloud decisionengine
deCertsMountRoot: config/de/certs


#-----------------------------------------------------------------------------------------------------------------------#
# PersistentMount paths: these values are the mount locations on the host machine of kubernetes PersistentMounts,       #
# which are read-writeable by pods and are preserved when pods are destroyed. They must be expressed as absolute paths. #
#-----------------------------------------------------------------------------------------------------------------------#

# condorCredsMountRoot is the absolute path to the directory containing passwords and tokens 
# for the HTCondor central manager. It is used to share credentials between pods in the cluster.
condorCredsMountRoot: .../persistent-mount/condor

# scitokenComplaintMount is the absolute path to the directory where the HEPCloud decisionengine will automatically generate
# a scitoken-complaint.log file. Failure to automatically renew scitokens will write warnings and further instructions to this file.
scitokenComplaintMount: .../persistent-mount/de/scitoken-complaint

# condorSpoolMount is the absolute path to the persistent mount directory for the HTCondor central manager spool
condorSpoolMount: .../persistent-mount/condor/spool
