language: python

# What versions of python do we test with
python:
  - "2.7"
  - "3.6"
  - "3.8"
  - "pypy"
  - "pypy3"

matrix:
  allow_failuers:
    # These don't need to work, but be nice if they did
    - python: "pypy"
    - python: "pypy3"

# command to install dependencies
install:
  - python -VV
  - pip install -r requirements.txt
  - pip install coveralls

# command to run tests
script:
  - pytest

# hook into coveralls
after_success:
  - coveralls

# add docker service hook
services:
  - docker
