language: python
os: linux

# What versions of python do we test with
python:
  - "2.7"
  - "3.6"
  - "3.8"
  - "pypy3"

jobs:
  allow_failures:
    # These don't need to work, but be nice if they did
    - python: "2.7"
    - python: "pypy3"

  fast_finish: true

# Just some useful info and prep work
before_install:
  - uname -a
  - pip install -U pip
  - pip install -U pytest

  # setup the 'simple major ver' link, missing for some versions on travis-ci....
  - if [[ ! -e /opt/python/${TRAVIS_PYTHON_VERSION} ]]; then
        cd /opt/python/;
        ln -s $(python -c 'import sys;print("%d.%d.%d" % sys.version_info[:3])') ${TRAVIS_PYTHON_VERSION};
    fi

# Environment variables
env:
  - LD_LIBRARY_PATH="${TRAVIS_BUILD_DIR}/framework/logicengine/"   PYTHON_PATH=$(dirname ${TRAVIS_BUILD_DIR})

# commands to install any dependencies
install:
  - sudo apt-get -y install cmake libboost-all-dev g++

    # Setup pkg-config and cmake search paths to use the virtualenv python from travis
  - export PKG_CONFIG_PATH="/opt/python/${TRAVIS_PYTHON_VERSION}/lib/pkgconfig"
  - export CMAKE_INCLUDE_PATH="/opt/python/${TRAVIS_PYTHON_VERSION}/include/python${TRAVIS_PYTHON_VERSION}m/include/;/opt/python/${TRAVIS_PYTHON_VERSION}/include/python${TRAVIS_PYTHON_VERSION}/include/;/opt/python/${TRAVIS_PYTHON_VERSION}/include/"
  - export CMAKE_LIBRARY_PATH="/opt/python/${TRAVIS_PYTHON_VERSION}/lib/;/opt/python/${TRAVIS_PYTHON_VERSION}/lib_pypy/"
  - export PYVER=$(python -c 'import sys; print("%d.%d" % (sys.version_info.major, sys.version_info.minor))')

  # run cmake and build logic engine
  - mkdir -p ${TRAVIS_BUILD_DIR}/framework/logicengine/cxx/build
  - cd ${TRAVIS_BUILD_DIR}/framework/logicengine/cxx/build
  - cmake -DPYVER=${PYVER} -DCMAKE_LIBRARY_PATH="${CMAKE_LIBRARY_PATH}" -DCMAKE_INCLUDE_PATH="${CMAKE_INCLUDE_PATH}" ..
  - make
  - make liblinks

  # pull in any listed python requirements
  - cd ${TRAVIS_BUILD_DIR}
  - pip install -r requirements.txt
  - pip install coveralls

# Just some useful info
before_script:
  - set

# command to run tests
script:
  - cd ${TRAVIS_BUILD_DIR}/../
  - pytest -v -l --tb=native

# hook into coveralls
after_success:
  - coveralls

# add docker service hook
services:
  - docker
