apiVersion: apps/v1
kind: Deployment
metadata:
  name: htcondor-cm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: htcondor-cm
  strategy:
    type: Recreate    
  template:
    metadata:
      labels:
        app: htcondor-cm
    spec:
      restartPolicy: Always
      containers:
      - name: htcondor-cm
        image: ahimley/htcondor-cm-8.9.11-el7:20220906
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "chown -R 64:64 /var/lib/condor/spool; /root/setup-creds.sh;"]
        ports:
        - containerPort: 9618 
        - containerPort: 51450
        - containerPort: 41450
        volumeMounts:
        - mountPath: /var/lib/condor/spool
          name: condor-spool
        - mountPath: /etc/condor/config.d/99-site.config
          name: condor-config
          subPath: 99-site.config
        - mountPath: /etc/condor/condor-mapfile
          name: condor-mapfile
          subPath: condor-mapfile
          readOnly: true
        - mountPath: /etc/condor/passwords.d/
          name: condor-passwd
        - mountPath: /etc/condor/tokens.d/
          name: condor-tokens
        - mountPath: /root/setup-creds.sh
          subPath: setup-creds.sh
          name: setup-creds
        - mountPath: /etc/grid-security/hostcert.pem
          subPath: hostcert.pem
          name: hostcert-secret
        - mountPath: /etc/grid-security/hostkey.pem
          subPath: hostkey.pem
          name: hostkey-secret
        resources:
          limits:
            cpu: 1
            memory: 2Gi
          requests:
            cpu: 350m
            memory: 1Gi
        env:
        - name: SERVICE_FQDN
          value: {{ .Values.hostHostname }}
      volumes:
        - name: hostcert-secret
          secret:
            secretName: certs-htcondor-cm
            defaultMode: 0600
            items:
            - key: hostcert.pem
              path: hostcert.pem
        - name: hostkey-secret
          secret:
            secretName: certs-htcondor-cm
            defaultMode: 0600
            items:
            - key: hostkey.pem
              path: hostkey.pem
        - name: condor-spool
          persistentVolumeClaim:
            claimName: htcondor-cm-pvc
        - name: condor-config
          configMap:
            name: htcondor-cm-config
            defaultMode: 0644
            items:
            - key: 99-site.config
              path: 99-site.config
        - name : condor-mapfile
          configMap:
            name: htcondor-cm-config
            defaultMode: 0644
            items:
            - key: condor-mapfile
              path: condor-mapfile
            optional: true
        - name: setup-creds
          configMap:
            name: htcondor-cm-config
            defaultMode: 0755
            items:
            - key: setup-creds.sh
              path: setup-creds.sh
        - name: condor-passwd
          persistentVolumeClaim:
            claimName: condor-passwd-pvc
        - name: condor-tokens
          persistentVolumeClaim:
            claimName: condor-tokens-pvc
