on: [pull_request, push]

jobs:
  unit_test_job:
    runs-on: ubuntu-latest
    name: A job to run unit tests
    steps:
    - uses: actions/checkout@v2
    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: 'decisionengine'
    - name: unit test action step
      id: unit_test
      uses: ./.github/actions/unittest-in-sl7-docker
    - name: Archive unittest log
      if: always()
      uses: actions/upload-artifact@v1
      with:
        name: test-log
        path: test.log
